apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: angular-image
    context: .
    sync:
      manual:
      - src: 'src/**/*'
        dest: '/src/'
    docker:
      dockerfile: skaffold/Dockerfile
deploy:
  kubectl:
    manifests:
    - skaffold/local.yaml
