apiVersion: v1
kind: Service
metadata:
  name: northwind-ui-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https
    targetPort: http
  selector:
    lfda-app-name: northwind-ui

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: northwind-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      lfda-app-name: northwind-ui
  template:
    metadata:
      labels:
        lfda-app-name: northwind-ui
    spec:
      containers:
        - name: northwind-ui
          image: gcr.io/cloud-solutions-images/northwindui:1.0.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LISTEN_PORT
              value: "8080" 
            - name: SERVER_NAME
              value: "_"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
