apiVersion: v1
kind: Service
metadata:
  name: course-frontend-svc
spec:
  type: NodePort
  ports:
  - nodePort: 30102
    port: 4200
    targetPort: http
  selector:
    cf-app-name: course-frontend
