apiVersion: v1
kind: Pod
metadata:
  name: course-frontend
  labels:
    cf-app-name: course-frontend
spec:
  containers: 
  - name: course-frontend
    image: course-frontend
    ports:
    - containerPort: 4200
      name: http
    # env:
    #   - name: LISTEN_PORT
    #     value: "4200"
    #   - name: SERVER_NAME
    #     value: "_"
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 4200
    #   initialDelaySeconds: 5
    #   periodSeconds: 5
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 4200
    #   initialDelaySeconds: 5
    #   periodSeconds: 5
# https://codinglatte.com/posts/angular/using-os-environment-variables-in-angular-with-docker/