apiVersion: v1
kind: Pod
metadata:
  name: course-frontend
  labels:
    lfda-app-name: course-frontend
spec:
  containers:
  - name: course-frontend
    image: course-frontend
    ports:
    - containerPort: 4200
      name: http
